services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: iu
      POSTGRES_PASSWORD: iu_password
      POSTGRES_DB: iu_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iu -d iu_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      bash -lc "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  db_data:
