#!/bin/bash
# Тестирование Flutter приложения

echo "=== Шаг 7: Мобильный клиент (Flutter) ==="
echo ""
echo "Flutter проект создан в папке iu_mobile/"
echo ""
echo "Добавлены зависимости:"
echo "- http (для API запросов)"
echo "- shared_preferences (для хранения токена)"
echo "- intl (для форматирования дат)"
echo ""
echo "Настроены разрешения для HTTP:"
echo "- Android: android/app/src/main/AndroidManifest.xml"
echo "- iOS: ios/Runner/Info.plist"
echo ""
echo "Создана структура приложения:"
echo "- lib/api.dart - API клиент"
echo "- lib/models.dart - модели данных"
echo "- lib/screens/auth/ - экран авторизации"
echo "- lib/screens/zones/ - список зон"
echo "- lib/screens/zone_layout/ - схема зала"
echo "- lib/screens/slots/ - выбор времени"
echo "- lib/screens/bookings/ - мои брони"
echo ""
echo "Для запуска приложения:"
echo "1. cd iu_mobile"
echo "2. flutter run"
echo ""
echo "Примечание: для подключения к localhost:"
echo "- Android эмулятор: используйте http://10.0.2.2:8000"
echo "- iOS симулятор: используйте http://localhost:8000"
echo "- Физическое устройство: используйте IP адрес компьютера"
echo ""
echo "Тестовые аккаунты:"
echo "- admin@example.com / adminpass123 (администратор)"
echo "- user@example.com / userpass123 (обычный пользователь)"